services:
  # Backend API Server
  backend:
    build: 
      context: ./server
      dockerfile: Dockerfile
    container_name: movie-app-backend
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=development
      - PORT=3001
      - TMDB_API_KEY=${TMDB_API_KEY}
      - FRONTEND_URL=http://localhost:5173
    volumes:
      - ./server:/app
      - /app/node_modules
    networks:
      - movie-app-network

  # Frontend React App
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: movie-app-frontend
    ports:
      - "5173:5173"
    environment:
      - VITE_API_BASE_URL=http://localhost:3001/api
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - backend
    networks:
      - movie-app-network

networks:
  movie-app-network:
    driver: bridge